addons:
  chrome: stable

sudo: false
language: node_js
node_js:
  - 12
branches:
  only:
    - master
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
  - echo "Add script to pack chrome extension"
