name: Lint

on: [push]



jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: install eslint
        run: sudo npm install --global eslint-config-standard
      - uses: actions/checkout@v1
      - uses: stefanoeb/eslint-action@1.0.2
